export enum DocumentType {
  EOTINISH = 'eOtinish',
  ROVD = 'rovd',
}

export enum CaseState {
  NEW = 'NEW',
  COLLECTING_INFORMATION = 'COLLECTING_INFORMATION',
  COLLECTING_EVIDENCE = 'COLLECTING_EVIDENCE',
  ANALYZING = 'ANALYZING',
  LEGAL_RESEARCH = 'LEGAL_RESEARCH',
  ACTION_PLAN_READY = 'ACTION_PLAN_READY',
  DRAFT_READY = 'DRAFT_READY',
}
